### ISSUE TITLE
Button Clikc Issue < iOs 16.3 

### ISSUE THREAD

**Issue by vekkon** [FriendsOfShopware/FroshPlatformFilterSearch#21] opened 2024-02-27 12:41 UTC
### PHP Version

8.1

### Shopware Version

6.5.8.6

### Plugin Version

2.0.1

### Actual behaviour

When the plugin is activated some click events are no longer triggered correctly on mobile devices. This issue occures only on iPhones with ios 16.3 or lower. Here are some examples of buttons/links which no longer work correctly with the plugin installed and activated:
- button: nav-main-toggle-btn
- buttone  search-toggle-btn
- button: account-menu-btn
- link: page-link

Important note: This issue did not occure on version 2.0.0. I now made a downgrade to have a working site for all devices.

### Expected behaviour

Button clicks should correctly be handled and filter plugin should not interfere with those events

### Steps to Reproduce?

Install filter plugin, test the above mentioned button with a ios device with ios 16.3 or lower.

**Comment by shyim** [comment] 2024-03-03 13:36
Can you try 2.0.4 and see if that fixes your problem?

**Comment by vekkon** [comment] 2024-03-27 13:30
Hi @shyim 
Unfortunataly version 2.0.4 does not solve the problem.

**Comment by sstieler** [comment] 2024-04-17 13:57
We have the same Problem. Error message in the browser console is 
Unexpected token '{' ..
and refers to the line in all.js where the FroshPlatformFilterSearch JavaScript is printed. 

Maybe that info helps somehow?

**Comment by sstieler** [comment] 2024-04-17 14:03
It refers to the following part of the JS

(() => {
    var o = class extends window.PluginBaseClass {
        static {       //<!--------------------------
            this.options = {
                dropdownSelector: ".filter-panel-items-container .dropdown"
            }
        }
        init() {

Chrome Version is 96.0

**Comment by schneider-felix** [comment] 2024-12-10 11:13
This issue is caused by using the `static initialization blocks` JS feature. It is an ES2022 feature and is not supported in iOS before 16.4. See: 
- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks)
- [Can I use](https://caniuse.com/mdn-javascript_classes_static_initialization_blocks)

This is quite weird because the static initialization block seems to be introduced during the TypeScript transpilation. But I really do not understand why. The target for the TS transpiler is set to ES2020. 

Do you have an idea what could be causing this behaviour @shyim ?

**Comment by shyim** [comment] 2024-12-10 12:09
i have no idea, I am not sure if this is a real world issue. apple released a ton of security updates on 16.x and people maybe have anyway upgraded to the latest 16.x.

**Comment by schneider-felix** [comment] 2024-12-10 12:11
Alright I agree. I will close this issue. If this is a problem anyone is encountering with real users, feel free to submit a PR.

**Closed as not planned by schneider-felix** 2024-12-10 12:11 UTC
Labels: kind/bug
